[package]
name = "HackNotts84"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4.31"
eframe = "0.23.0"
egui = "0.23.0"
reqwest = { version = "0.11", features = ["blocking","json"]}
serde = { version = "1.0.190", features = ["derive"] }
